CREATE TABLE IF NOT EXISTS Usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Biblioteca (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    endereco TEXT
);

CREATE TABLE IF NOT EXISTS Livro (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo TEXT NOT NULL,
    autor TEXT,
    isbn TEXT UNIQUE,
    biblioteca_id INTEGER,
    FOREIGN KEY (biblioteca_id) REFERENCES Biblioteca(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Teste (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    resultado TEXT,
    usuario_id INTEGER,
    FOREIGN KEY (usuario_id) REFERENCES Usuario(id) ON DELETE SET NULL
);